batch_size: 12
class_weights: !!python/object/apply:numpy._core.multiarray._reconstruct
  args:
  - !!python/name:numpy.ndarray ''
  - !!python/tuple
    - 0
  - !!binary |
    Yg==
  state: !!python/tuple
  - 1
  - !!python/tuple
    - 6
  - !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - false
  - !!binary |
    WLsZouwI6T+hfWnja//pP6b04cAIJPg/QiueIAbm4D94lB+Bf7nuPwKPfSsIiPY/
hidden_channels: 64
input_dim: 8
lr: 0.001
num_classes: 6
weight_decay: 0.0001
